name = "SDDPlab"
uuid = "5c1c4b2a-157d-4661-af07-65cbafd6173d"
version = "2.0.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Copulas = "ae264745-0b69-425e-9d9d-cf662c5eec93"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Parquet = "626c502c-15b0-58ad-a749-f091afb673ae"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SDDP = "f4570300-c277-11e8-125c-4912f86ce65d"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[weakdeps]
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"

[compat]
GLPK = "1.2.1"

[extras]
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["GLPK", "Test", "Suppressor"]
